logging:
  out_path: 'out/path_integration/1D/grid_search/design_choices/discrete'
  save_keys: null
  grid_search:
    n_samples: 1
    run: ['train', 'kqgr']
model:
  input_layer:
    w_bi: identity
    w_ir: identity
    pertubation: [override, xor]
    encoding: [base2, binary_embedding, primes]
    features: 1 # affects how redundancy is applied
    redundancy: [1, 2, 3] # changes the task complexity
    resolution: 3
    chunks: 1
    ticks: ['1', '2']
  output_layer:
    n_outputs: 1 # no effect on kq and gr
  reservoir_layer:
    init: [zeros, random, random-warmup]
    k_avg: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
    k_min: 0
    k_max: 'k_avg + 3 * k_avg ** .5' # 3 std of binomial distribution
    mode: [homogeneous, heterogeneous]
    n_nodes: [512, 1024] # make sure 2**D.bits-1 >= n_nodes to have enough states
    reset: true
    self_loops: [0, .1, .3, .5, 1] # interesting number of attractors
  training:
    accuracy_threshold: 0.25 # ~ sqrt(2) / (2**3 - 1) diagonal + neighbour grids are considered a "hit"
    batch_size: 128
    criterion: MSE
    epochs: 40
    evaluation: dev
dataset:
  coordinate: cartesian
  dimensions: 1
  steps: 5
  strategy:
    name: PhysicsWalkStrategy
    params:
      max_force: 0.5
      mass: 1.0
      friction_coeff: 0.1
      friction_order: 2
      max_speed: 10
  boundary:
    name: IntervalBoundary
  split:
    train: 0.5
    dev: 0.3
    test: 0.2
  samples: 30000
  seed: 0
multiverse_overrides:
  kqgr_PI: # add/override these fields for KQGR
    dataset:
      evaluation: [first, last, random]
      tau: 1
  kqgr_T: # mirrors temporal grid search but with no training
    dataset:
      name: temporal # make sure this isnt PI
      evaluation: [first, last, random]
      tau: [3, 5]
      task: density
      sampling_mode: 'exhaustive'
      shuffle: True # avoid bug: n_nodes = 512, bits=10 → dataset loads first 512/1024 samples; all start with "0"
      seed: 0
    model:
      input_layer:
        features: 1
        redundancy: [1, 2, 3] # changes the task complexity
        resolution: 10 # set to 10 so we get 1024 input combinations when testing R.n_nodes=1024
        chunk_size: 1 # one bit at a time
        chunks: null # force re-calculate
        bits: null # force recalculation from features * resolution * redundancy
    logging:
      grid_search:
        run: ['kqgr']